### ISSUE TITLE
Seo Image is showing GDG DevFest image in social media posts

### ISSUE THREAD

**Issue by bhuvankrishna** [gdg-x/zeppelin#103]
Even after changing the images in img/seo/ and other places when sharing in social media the image is showing GDG DevFest 2014 image.

**Comment by giantthinker** [comment]
@bhuvankrishna try to push your changes or clear the cache of your browser.

**Comment by bhuvankrishna** [comment]
We did every thing from clearing the cache to removing images svg/png related to the image that is showing up in the social media posts. even this site is showing the image http://iwd.gdgnorthjersey.com/womeninnovation/ 

May be they did not change but we have changed everything and still get GDG DevFest image in the shared post

**Comment by giantthinker** [comment]
Try to use the same filename when when renaming your social images and delete the previous ones so that your new images should appear instead. I hope this might solve the problem.

**Comment by bhuvankrishna** [comment]
That's right we replaced the images and did not change the file names even then we are getting the same image. Is there any code in the template which points to these images outside the template? or is it that some js file is pulling in the images from a different location? or is it that the cache of the social networks need to refresh? right Now we have no clueless. I am going through the source hopping to find a reference to these images other than img/seo/. If you or any one can help in checking the code and see if any link is pointing to external link that would be of great help.

**Comment by giantthinker** [comment]
I find no place where the images are from outside. Please try another browser and see if the same thing happens.

**Comment by bhuvankrishna** [comment]
Ok its not just the problem of posting in browser. for instance when I share the link in telegram the image shows, when I share it in facebook or twitter the updated image is showing. and in some browsers its showing the GDG image.

**Comment by giantthinker** [comment]
Then it means it's cache problem in those browsers I guess. Clear cache and cookies.

**Comment by ozasadnyy** [comment]
@bhuvankrishna please send us link to repo with the source code

**Comment by bhuvankrishna** [comment]
This is where the code is hosted. https://code.swecha.org/shashikanth171/devcon

**Comment by bhuvankrishna** [comment]
One more issue that we are also face is embedding map which is already reported. We tried many things but nothing worked out. #98

**Comment by ozasadnyy** [comment]
@bhuvankrishna everything looks okay, so it should be a problem with the deploy. Please double check build folder and deploy process. If it's not the issue, please reopen the issue.

**Comment by bhuvankrishna** [comment]
Thank you every for helping out. The problem is still there. @ozasadnyy we will check the deploy and pages stages maybe something is not working there and get back.
