### ISSUE TITLE
feature request: web search

### ISSUE THREAD

**Issue by rriemann** [gdg-x/zeppelin#111]
Hello,

it would be interesting if website visitors would find an easy solution to search speakers, events and blog posts. The jekyll theme https://mmistakes.github.io/minimal-mistakes/ has recently integrated a js client-side search based on https://github.com/olivernn/lunr.js .

**Comment by ozasadnyy** [comment]
Hello @rriemann, thanks for the suggestions but I don't think that conference website really needs a search. We focus on speed, on the other hand, a search can affects negatively on it.

**Comment by rriemann** [comment]
From a previous experience with a conference homepage, I learnt that it can be handy to find the session/speaker easily of a multi-track and multi-day conference.

**Comment by ozasadnyy** [comment]
@rriemann unfortunately, our team will not implement this feature as it's more like edge case rather than regular usage. Feel free to fork repository, develop the feature and share globally
