### ISSUE TITLE
For App Engine...

### ISSUE THREAD

**Issue by raphaelsavina** [gdg-x/zeppelin#31]
Just something to add to the documentation. If any of you still want to us App Engine, here is the app.yaml to use. Assuming the site is at the root, you have:
baseurl: "" in your _config.yml.

application: [name of your app here]
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico

- url: /blog/(.+)
  static_files: blog/\1/index.html
  upload: blog/\1/index.html

- url: /(.+)/
  static_files: \1/index.html
  upload: \1/index.html

- url: /
  static_files: index.html
  upload: index.html

- url: /(.+)
  static_files: \1
  upload: (.+)

**Comment by ozasadnyy** [comment]
Closed due to inactivity.
