### ISSUE TITLE
Thumbor integration

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/zeppelin#60]
I was thinking about this a lot and I would like to get your opinion before implementing anything. 

There is an open source project called [thumbor](https://github.com/thumbor/thumbor) for image optimization in web sites. 

Right now while I develop [WTM Istanbul 2015](http://wtmistanbul.com) I take my time to optimize the images. But I remember that we didn't do much for [DevFest Istanbul](http://devfesttr.com). Especially it is really hard when all of the organizers are busy with the event. 

With thumbor, since we compute the sizes of every image when we draw them, we can give it to thumbor and it optimizes them and cache them in the server. After the first time the webpage is open, all the images become optimized. And you can also store images with effect like grayscale to be even faster. 

The downside of it is that it has to be installed manually on a server. I know we cannot have a central server for everyone. What we can have is to have a wiki page about how to install thumbor and just enable it by providing a thumbor server URL in the config. 

What do you think?

**Comment by ozasadnyy** [comment]
Hello @tasomaniac .The main disadvantage of this purpose is that you need server and it's bad..
I have a different approach. I am working on the new version - [Zeppelin-grunt](https://github.com/ozasadnyy/zeppelin-grunt) where grunt will optimize all images during the build.

**Comment by tasomaniac** [comment]
Wow the demo of the grunt version is lot lot faster. Great! :)

Optimization during build is really cool and will solve most of the part of this issue. 

But thumbor also resize your images to multiple sizes depends on where and which size you use them. So for example our sponsors and speakers gives use like 8MP images, optimization does not resize them but thumbor does. :) But I guess there can be a little bit manual work for now. 

You are right about disadvantage of having a server. The purpose of this project actually conflicts with it.

**Comment by ozasadnyy** [comment]
The best way is to use SVG for sponsors' logos)
Ok, I am closing this issue.
